import type { OwnedVehicle } from '@common/types';

export const mockupVehicles: OwnedVehicle[] = [
  {
    id: '1',
    plate: 'ABC123',
    owner: 'John Doe',
    model: 'adder',
    stored: 'pillbox',
  },
  {
    id: '2',
    plate: 'XYZ789',
    owner: 'Jane Smith',
    model: 'nero',
    stored: null,
  },
  {
    id: '3',
    plate: 'LMN456',
    owner: 'Alice Johnson',
    model: 'euros',
    stored: 'impound',
  },
  {
    id: '4',
    plate: 'QWE123',
    owner: 'Bob Brown',
    model: 'brioso3',
    stored: 'north_korea',
  },
  {
    id: '5',
    plate: 'RTY456',
    owner: 'Charlie Davis',
    model: 'fake',
    stored: null,
  },
  {
    id: '6',
    plate: 'GHJ234',
    owner: 'Eve Black',
    model: 't20',
    stored: 'garage',
  },
  {
    id: '7',
    plate: 'BNM897',
    owner: 'Frank White',
    model: 'entityxf',
    stored: 'airport',
  },
  {
    id: '8',
    plate: 'VBN564',
    owner: 'Grace Green',
    model: 'osiris',
    stored: 'downtown',
  },
  {
    id: '9',
    plate: 'POI674',
    owner: 'Hank Orange',
    model: 'itali',
    stored: null,
  },
  {
    id: '10',
    plate: 'KJL345',
    owner: 'Irene Pink',
    model: 'reaper',
    stored: 'hospital',
  },
  {
    id: '11',
    plate: 'WER567',
    owner: 'Jake Blue',
    model: 'zentorno',
    stored: 'impound',
  },
  {
    id: '12',
    plate: 'DFH678',
    owner: 'Kelly Grey',
    model: 'tempesta',
    stored: 'school',
  },
  {
    id: '13',
    plate: 'UIO789',
    owner: 'Liam Violet',
    model: 'vacca',
    stored: 'casino',
  },
  {
    id: '14',
    plate: 'TYU890',
    owner: 'Mia Cyan',
    model: 'buffalo',
    stored: null,
  },
  {
    id: '15',
    plate: 'ZXC234',
    owner: 'Noah Olive',
    model: 'sultanrs',
    stored: 'beach_house',
  },
];
